name: Update Neofetch Card

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    paths:
      - "scripts/update_card.js"
      - "aritro-neofetch.svg"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          npm init -y >/dev/null 2>&1 || true
          npm i @octokit/rest @octokit/graphql jsdom

      - name: Update SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOB_ISO: ${{ secrets.DOB_ISO }}
        run: node scripts/update_card.js

      - name: Debug
        run: |
          ls -la
          git status

      - name: Commit changes
        if: success()
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add aritro-neofetch.svg
            git commit -m "chore: update aritro-neofetch [skip ci]"
            git push
          fi
